version: "3"
services:
  grecom_frontend:
    container_name: grecom_frontend
    restart: always
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - grecom_backend
      - grecom_group_backend
    depends_on:
      - grecom_backend
      - grecom_group_backend
  grecom_backend:
    container_name: grecom_backend
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    links:
      - grecom_group_backend
    depends_on:
      - grecom_group_backend
    environment:
      - PORT=5000
  grecom_group_backend:
    container_name: grecom_group_backend
    restart: always
    build:
    build:
      context: groupBackend
      dockerfile: Dockerfile
    volumes:
      - ./backend/assets:/app/assets
    ports:
      - "8081:8888"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongo:27017/grecom
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"