version: "3"
services:
  grecom_frontend:
    container_name: coux_frontend
    restart: always
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - grecom_backend
    depends_on:
      - grecom_backend
  grecom_backend:
    container_name: grecom_backend
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:4000"
    environment:
      - PORT=4000
